apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votingapp-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
  - hosts:
      - bua002.contoso.com
    secretName: bua002-tls-secret
  rules:
  - host: bua002.contoso.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: azure-vote-front
            port:
              number: 80
        pathType: Exact